### ISSUE TITLE
Requirements for and Expected Costs of Hosting an Instance of Anonymous GitHub 

### ISSUE THREAD

**Issue by LennartPurucker** [tdurieux/anonymous_github#147]
Heyho,

First, thank you for your hard work on this project and for hosting Anonymous GitHub for free.

I am thinking about hosting an instance of Anonymous GitHub for a conference to enable downloading of larger repositories (as described in #24) and was wondering about hardware requirements and expected costs. 

I read that "the server costs [...] hundreds of dollars per year". 
Could you perhaps elaborate on this? What hardware are you using, and what costs could I expect for 100s of repositories over 6 months?

**Comment by tdurieux** [comment]
I am paying 35€/months for my server. It is an 8 cores (AMD EPIC), 8gb ram. And I am using a object storage for caching the repositories (aws API). I am using 70gb of storage for the moment. 
You do not need the object storage, you can just use the filesystem (see configuration).

My installation is also behind cloudflare and a ngnix server.

Depending of your provider you can expect to pay 200$ for the six months. I would recommend you to take a server to an known providers to offer a good service to most countries.

You should assume that you will have some difficulties since you will likely be the first one to deploy an instance.

**Comment by LennartPurucker** [comment]
Thank you very much for the detailed answer! This gives me a good understanding of what to expect. 

I will try to document the process and report to you on how difficult it was. Maybe this can help others in the future.
