### ISSUE TITLE
XXX does not work with Paths

### ISSUE THREAD

**Issue by TortugaAttack** [tdurieux/anonymous_github#20]
We usually use our group name in the package paths. 
E.g. org.GROUP.SUB_GROUP.projectname 

And everything works fine for me, except that the replacement does not work in the actual URL path 
![anon](https://user-images.githubusercontent.com/5443313/54345772-02c9a280-4644-11e9-99d5-ad69a522fa6a.png)

**Comment by tdurieux** [comment]
I thought about this problem, and I don't have an easy solution to address it for the moment.
I cannot simply replace the content of the URL with XXX because I will not know how to access the content in GitHub. 
I would need to implement a much more complex anonymization strategy for the URL and keep much more state on the server side. 
I would like to avoid this as much as possible to reduce the server overhead and cost. 

I would be happy to hear suggestions to address this issue.

**Comment by TortugaAttack** [comment]
I see, 

I am not completely sure, but maybe encrypting the url. 
f.e. src/main/resource/ -> rtcxV6CltYVLOfzVYUrvEUGCUHuxVWFM (using blowfish f.e. with a key) 
Then you can decrypt it server wise and get the github url.

**Comment by tdurieux** [comment]
It is indeed one option. I liked the idea of having a "readable" url. 
I will think more about how I can implement this.

Thanks for the issue

**Comment by TortugaAttack** [comment]
Another Idea: 
https://anonymous.4open.science/repository/REPOID/ENCRYPTED_PATH/src/main/resources/XXX_group 
So you have the ENCRYPTED PATH which you can use for getting the actual repository path, and the readable URL but with the replacement.

**Comment by tdurieux** [comment]
Good idea, I think I have an idea that should also not break the retro-compatibility. I will try to find some time to implement it.
