### ISSUE TITLE
Can I disable the "Download Repository" function of my own repository?

### ISSUE THREAD

**Issue by LixiaoTHU** [tdurieux/anonymous_github#289]
Please see the title

**Comment by tdurieux** [comment]
Unfortunately, it is not possible because some tools allow downloading each individual file from an anonymous GitHub repository. 
It would be extremely tricky to block them. Additionally, those tools add a high load on the system and make it unstable, providing this feature increases the reliability of the service without practical change for the researchers and reviewers
