### ISSUE TITLE
Git clone support

### ISSUE THREAD

**Issue by GoingMyWay** [tdurieux/anonymous_github#43]
Hi, this repo is really great for us to share anonymous code for academic conferences. Will you add git clone support so that we can clone the code?

**Comment by nslay** [comment]
Yeah, I thought you could just clone this with normal git clone. I found this tool which mostly solves the problem:
https://github.com/ShoufaChen/clone-anonymous4open

But just so you know... it will not actually clone your README.md. If you make a supplementary zipfile with the anonymous.4open.science cloned repository through that tool, it will not have a README (even if it says it cloned the file). Be very careful! I included the anonymous.4open.science link as a footnote in my paper. Hopefully reviewers will notice it... maybe that's wishful thinking!

Yeah, I feel a bit shafted by both of these tools.

- anonymous.4open.science files are very hard to access without a tool like clone-anonymous4open. If you inspect the web content (or save-as a file link), the files are heavily decorated with HTML tags and all that jazz. It's a wonder tools can even process this! A human would have a hard time dealing with this (probably would have to manually copy/paste text from the file preview to a text file).
- clone-anonymous4open does not clone *.md files (like README.md).

So be very careful. These two tools can really mess your submission up **real bad**. Either by making it impossible for reviewers to actually get at the files and run them (because there's no obvious way to download the raw content from anonymous.4open.science). Or by not cloning crucial documentation (README.md) for reviewers to reproduce your results.

**Comment by tdurieux** [comment]
Yes, anonymous4open was not meant to be cloned. I am considering creating a new version that would allow something like this. The issue is the lack of time. Hopefully, this will happen eventually. I also need to find a way to cover the cost of the server.
