### ISSUE TITLE
Subdirectories containing index files are rendered as site root

### ISSUE THREAD

**Issue by micahjsmith** [tdurieux/anonymous_github#49]
Suppose you anonymize a repo with the following directory structure:

```
/
/docs
/docs/index.rst
/docs/conf.py
/docs/some_guide.rst
```

When a viewer clicks on `docs/` they are shown a rendering of the `index.rst` file rather than a folder view listing all of the files in the directory. So a viewer cannot view `some_guide.rst` unless they know to type in the relative path in the browser navigation bar.

Suggested resolution: every directory should have the same experience as `/`
* the directory path should be displayed in the top bar
* the list of files within the directory should be displayed below it
* if the directory has a file that is known to be the highest-level documentation (i.e. `README.*`, `index.*`), then that file should be rendered below the file list

Thanks!

**Comment by tdurieux** [comment]
Thank for the issue.
I know this, I hardcoded this for my repositories. I frequently use github page in /docs.
This will not be fixed in the v1 but this problem will not happen in the v2. Github pages will have a different URL than the repository.
I hope to deploy the v2 in the next days. I just need more people to test the new version.
